<a href="https://colab.research.google.com/github/eturba/employee-layoffs-analysis/blob/main/GB885_Assignment_5_Turba_E.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment 5 - Chef's Choice

### Eric Turba

For this project, I will be using a Job Layoffs Dataset that contains information on companies that laid off employees between 2020 and 2023.

The dataset includes details on layoffs such as company information, industry, location, company stage, funding raised, total employees laid off, and percentage of workforce impacted.

The dataset can be found here: (https://github.com/eturba/Layoffs-Dataset/blob/main/layoffs%20(1).csv)

## Problem Definition

**Business Case**: Identifying the Characteristics of Companies Most Vulnerable to Large-Scale Layoffs

In recent years, layoffs have become increasingly common across many industries. Investors, business analysts, and company executives need to understand whether certain types of companies are more likely to conduct significant layoffs. This dataset contains information on companies that announced layoffs, including their industry, location, funding raised, company stage, country, and the number and percentage of employees laid off.

The primary business question for this project is:

**What company characteristics are associated with the largest layoffs, and are there identifiable patterns based on industry, company stage, funding raised, or geographic location?**

Answering this question can help stakeholders identify which sectors or company types may face higher workforce reduction risks. The findings could support investment decisions, workforce planning, market analysis, and risk assessment by highlighting trends among companies experiencing major layoffs.

**Objectives of the analysis include**:

- Determine which industries experienced the highest number of layoffs.
- Identify whether certain company stages (e.g., Series A, Series E, Post-IPO) are associated with larger layoffs.
- Examine whether companies that raised more funding were less or more likely to conduct large layoffs.
- Compare layoff trends across countries and major geographic regions.
Explore how layoff activity changed over time throughout the dataset.

Before beginning the analysis, we will first import the dataset into Python. Since this project only contains a single data source, there is no need to combine or consolidate multiple datasets.

In [27]:
import pandas as pd
import numpy as np

# Load dataset directly from GitHub
url = "https://raw.githubusercontent.com/eturba/Layoffs-Dataset/refs/heads/main/layoffs%20(1).csv"

df = pd.read_csv(url)

# Preview the data
df.head()

,company,location,industry,total_laid_off,percentage_laid_off,date,stage,country,funds_raised_millions
0,Atlassian,Sydney,Other,500.0,0.05,3/6/2023,Post-IPO,Australia,210.0
1,SiriusXM,New York City,Media,475.0,0.08,3/6/2023,Post-IPO,United States,525.0
2,Alerzo,Ibadan,Retail,400.0,NaN,3/6/2023,Series B,Nigeria,16.0
3,UpGrad,Mumbai,Education,120.0,NaN,3/6/2023,Unknown,India,631.0
4,Loft,Sao Paulo,Real Estate,340.0,0.15,3/3/2023,Unknown,Brazil,788.0

## Data Inspection

Our first step will be to become familiar with the structure and contents of the dataset. We will begin by examining the number of rows and columns to understand the size of the dataset. Next, we will review the first and last five rows to get an initial look at the data

In [28]:
# Check number of rows and columns
print(f"Rows: {df.shape[0]}")
print(f"Columns: {df.shape[1]}")

Rows: 2361
Columns: 9

In [29]:
# Look into first 5 rows
df.head()

,company,location,industry,total_laid_off,percentage_laid_off,date,stage,country,funds_raised_millions
0,Atlassian,Sydney,Other,500.0,0.05,3/6/2023,Post-IPO,Australia,210.0
1,SiriusXM,New York City,Media,475.0,0.08,3/6/2023,Post-IPO,United States,525.0
2,Alerzo,Ibadan,Retail,400.0,NaN,3/6/2023,Series B,Nigeria,16.0
3,UpGrad,Mumbai,Education,120.0,NaN,3/6/2023,Unknown,India,631.0
4,Loft,Sao Paulo,Real Estate,340.0,0.15,3/3/2023,Unknown,Brazil,788.0

In [30]:
# Look into last 5 rows
df.tail()

,company,location,industry,total_laid_off,percentage_laid_off,date,stage,country,funds_raised_millions
2356,Blackbaud,Charleston,Other,500.0,0.14,NaN,Post-IPO,United States,NaN
2357,Yahoo,SF Bay Area,Consumer,1600.0,0.20,2/9/2023,Acquired,United States,6.0
2358,Hibob,Tel Aviv,HR,70.0,0.30,3/30/2020,Series A,Israel,45.0
2359,Casper,New York City,Retail,NaN,NaN,9/14/2021,Post-IPO,United States,339.0
2360,Wildlife Studios,Sao Paulo,Consumer,300.0,0.20,11/28/2022,Unknown,Brazil,260.0

Next, we will examine the data types for each column.

In [31]:
# Check data types
df.dtypes

company                   object
location                  object
industry                  object
total_laid_off           float64
percentage_laid_off      float64
date                      object
stage                     object
country                   object
funds_raised_millions    float64
dtype: object

It looks like the **date** column is currently stored as an object data type. We will make a note to convert this column into a datetime format during the data-cleaning phase to ensure dates are properly structured for analysis.

Next, we will generate descriptive statistics for the numerical columns to better understand the distribution, range, and overall characteristics of the dataset.

In [32]:
# Generate descriptive statistics
df.describe()

       total_laid_off  percentage_laid_off  funds_raised_millions
count     1621.000000          1576.000000            2152.000000
mean       238.358421             0.257917             822.454134
std        769.718801             0.255575            5593.961626
min          3.000000             0.000000               0.000000
25%         36.000000             0.100000              50.000000
50%         80.000000             0.170000             156.500000
75%        180.000000             0.300000             445.000000
max      12000.000000             1.000000          121900.000000

Looking at the descriptive statistics, the values in the **total_laid_off** and **percentage_laid_off** columns appear to be reasonable and consistent with expectations.

However, the maximum value in the **funds_raised_millions** column of 121,900 million stands out as unusually high compared to the mean. To better understand whether this value is accurate or a potential data issue, let's investigate which company raised this amount and verify the information.

In [33]:
# Filter the data frame for the company that raised 121900 million
df[df["funds_raised_millions"] == 121900]

,company,location,industry,total_laid_off,percentage_laid_off,date,stage,country,funds_raised_millions
973,Netflix,SF Bay Area,Media,30.0,NaN,9/14/2022,Post-IPO,United States,121900.0
1393,Netflix,SF Bay Area,Media,300.0,0.03,6/23/2022,Post-IPO,United States,121900.0
1582,Netflix,SF Bay Area,Media,150.0,0.01,5/17/2022,Post-IPO,United States,121900.0
1617,Netflix,SF Bay Area,Media,25.0,NaN,4/28/2022,Post-IPO,United States,121900.0

**Netflix** is the company with a reported 121,900 million (or 121.9 billion) in funding raised. When comparing this figure to Netflix's current market capitalization of approximately 290 billion, the amount appears reasonable and aligns with the scale of the company.

Next, lets check the value count for each column to see if we can spot any erroneous data.

In [34]:
# Count the number of values for each column
categories = df.select_dtypes(include="object").columns

for col in categories:
    print(f"\n----- {col.upper()} -----")
    print(df[col].value_counts(dropna=False))

----- COMPANY -----
company
Loft           6
Swiggy         5
OYO            5
Uber           5
Shopify        4
              ..
Meta           1
ZenBusiness    1
Wavely         1
SendCloud      1
EverBridge     1
Name: count, Length: 1893, dtype: int64

----- LOCATION -----
location
SF Bay Area      614
New York City    249
Boston           109
Los Angeles       93
Bengaluru         81
                ...
Prague             1
Yangon             1
New Orleans        1
Tampa Bay          1
Charleston         1
Name: count, Length: 191, dtype: int64

----- INDUSTRY -----
industry
Finance            284
Retail             195
Healthcare         183
Transportation     148
Food               141
Marketing          139
Other              129
Consumer           118
Real Estate        117
Crypto              99
Media               95
Education           93
Data                79
Security            74
Travel              66
HR                  66
Support             43
Infrastructure      43
Logistics           42
Sales               37
Product             35
Fitness             31
Recruiting          28
Hardware            17
Construction        16
Legal               13
Energy              12
Aerospace            6
NaN                  4
Fin-Tech             3
Manufacturing        2
Crypto Currency      2
CryptoCurrency       1
Name: count, dtype: int64

----- DATE -----
date
4/2/2020     27
4/3/2020     25
1/18/2023    24
3/27/2020    23
4/1/2020     21
             ..
5/8/2020      1
4/4/2020      1
3/12/2020     1
3/11/2020     1
NaN           1
Name: count, Length: 484, dtype: int64

----- STAGE -----
stage
Post-IPO          428
Unknown           393
Series B          305
Series C          303
Series D          225
Series A          177
Acquired          172
Series E          125
Series F           65
Seed               65
Private Equity     38
Series H           24
Series G           15
Series J            8
Series I            7
NaN                 6
Subsidiary          5
Name: count, dtype: int64

----- COUNTRY -----
country
United States           1541
India                    148
Canada                    99
Brazil                    77
United Kingdom            74
Germany                   68
Israel                    56
Australia                 54
Singapore                 34
Indonesia                 24
Sweden                    20
China                     18
Nigeria                   15
Netherlands               13
France                     7
Argentina                  6
United Arab Emirates       6
Kenya                      6
Estonia                    5
Ireland                    5
Hong Kong                  5
Colombia                   4
Mexico                     4
Denmark                    4
Norway                     4
Finland                    4
Seychelles                 4
United States.             4
Vietnam                    3
Austria                    3
Pakistan                   3
Chile                      3
Spain                      3
Portugal                   3
Luxembourg                 3
Malaysia                   3
Switzerland                2
Egypt                      2
South Korea                2
New Zealand                2
Italy                      1
Japan                      1
Poland                     1
Greece                     1
Hungary                    1
Belgium                    1
Thailand                   1
Lithuania                  1
Senegal                    1
Ghana                      1
Peru                       1
Bahrain                    1
Romania                    1
Turkey                     1
Russia                     1
Uruguay                    1
Bulgaria                   1
South Africa               1
Czech Republic             1
Myanmar                    1
Name: count, dtype: int64

After reviewing the unique values in the dataset, I identified two inconsistencies that will need to be addressed during the data-cleaning process:

- The **industry** column contains three different variations for cryptocurrency-related companies: "Crypto," "Crypto Currency," and "CryptoCurrency." These values should be standardized into a single category to ensure consistency.
- The **country** column contains two variations for the United States: "United States" and "United States." The extra period creates a duplicate category and should be corrected.

We will standardize these values during the cleaning process to improve data consistency and accuracy.

Now let's check for missing values in the data.

In [35]:
# Check for missing values
missing = pd.DataFrame({
    "Missing Values": df.isnull().sum(),
    "Percent Missing": round(df.isnull().mean()*100,2)
})

print(missing.sort_values("Missing Values", ascending=False))

                       Missing Values  Percent Missing
percentage_laid_off               785            33.25
total_laid_off                    740            31.34
funds_raised_millions             209             8.85
stage                               6             0.25
industry                            4             0.17
date                                1             0.04
company                             0             0.00
location                            0             0.00
country                             0             0.00

There appear to be a significant number of missing values across the dataset, particularly in the **percentage_laid_off**, **total_laid_off**, and **funds_raised_millions** columns. Since the dataset does not include total employee counts for each company, calculating missing layoff percentages would require additional external research. Given the large number of missing values and the scope of this project, we will leave these values as null for now.

We will also make a note to address the missing values in the **stage, industry,** and **date** columns during the data-cleaning phase.

Next, we will check the dataset for duplicate records.

In [36]:
# Check for duplicates
duplicates = df.duplicated().sum()
print(f"Duplicate Rows: {duplicates}")
if duplicates > 0:
    print(df[df.duplicated(keep=False)])

Duplicate Rows: 5
               company       location        industry  total_laid_off  \
118              Yahoo    SF Bay Area        Consumer          1600.0
625   Wildlife Studios      Sao Paulo        Consumer           300.0
1491             Cazoo         London  Transportation           750.0
1492             Cazoo         London  Transportation           750.0
1689            Casper  New York City          Retail             NaN
2254             Hibob       Tel Aviv              HR            70.0
2357             Yahoo    SF Bay Area        Consumer          1600.0
2358             Hibob       Tel Aviv              HR            70.0
2359            Casper  New York City          Retail             NaN
2360  Wildlife Studios      Sao Paulo        Consumer           300.0

      percentage_laid_off        date     stage         country  \
118                  0.20    2/9/2023  Acquired   United States
625                  0.20  11/28/2022   Unknown          Brazil
1491                 0.15    6/7/2022  Post-IPO  United Kingdom
1492                 0.15    6/7/2022  Post-IPO  United Kingdom
1689                  NaN   9/14/2021  Post-IPO   United States
2254                 0.30   3/30/2020  Series A          Israel
2357                 0.20    2/9/2023  Acquired   United States
2358                 0.30   3/30/2020  Series A          Israel
2359                  NaN   9/14/2021  Post-IPO   United States
2360                 0.20  11/28/2022   Unknown          Brazil

      funds_raised_millions
118                     6.0
625                   260.0
1491                 2000.0
1492                 2000.0
1689                  339.0
2254                   45.0
2357                    6.0
2358                   45.0
2359                  339.0
2360                  260.0

There are five duplicate rows identified in the dataset that should be removed to ensure each record is unique. We will make a note to eliminate these duplicate entries during the data-cleaning phase.

Next, we will check for any leading or trailing spaces within the dataset. If any are found, we will trim those values to remove unnecessary spaces and improve data consistency.

In [37]:
# Check for leading/trailing spaces
for col in categories:

    spaces = (
        df[col]
        .dropna()
        .astype(str)
        .str.startswith(" ")
        |
        df[col]
        .dropna()
        .astype(str)
        .str.endswith(" ")
    ).sum()

    print(f"{col}: {spaces}")

company: 11
location: 0
industry: 0
date: 0
stage: 0
country: 0

There are 11 values in the dataset containing extra spaces that should be removed to improve consistency. We will make a note to address these formatting issues during the data-cleaning phase.

Finally, we will use the Interquartile Range (IQR) method to identify and count any statistical anomalies or potential outliers within the dataset.

In [38]:
#We will use the IQR method for this business case
#write a function to calculate IQR and print rows with values that fall outside that IQR

def count_iqr_outliers(df, column):
    # define q1
    q1 = df[column].quantile(0.25)
    # define q3
    q3 = df[column].quantile(0.75)
    # define iqr
    iqr = q3 - q1
    # define outlier thresholds
    l_threshold = q1 - 1.5 * iqr
    u_threshold = q3 + 1.5 * iqr
    # dount outliers
    outliers = (df[column] < l_threshold) | (df[column] > u_threshold)
    # Count the number of True values (outliers)
    return outliers.sum()

In [39]:
#iterate over the numerical columns of the dataframe:
num_var = list(df.select_dtypes(include=['int64', 'float64']).columns)

for column in num_var:
    print(f'{column} : {count_iqr_outliers(df, column)}')

total_laid_off : 175
percentage_laid_off : 153
funds_raised_millions : 219

It looks like we have numerous outliers across all three numerical variables. This result is somewhat expected because the dataset includes companies of vastly different sizes. As a result, companies with exceptionally large workforces and layoff events, such as Netflix, appear as statistical outliers.

These observations likely represent legitimate business events rather than data errors and should be retained for analysis, as they provide valuable insight into large-scale layoffs.

## Cleaning the Data

### Change Date Column to Datetime Format

Now that we have completed the data inspection process, we can begin cleaning the dataset.

The first step will be to convert the **date** column into a datetime format. This will ensure the column is properly structured for future analysis and allow us to perform date-based operations more efficiently.

In [40]:
# Change date column type to datetime
df["date"] = pd.to_datetime(df["date"], errors="coerce")

# Verify change have been made
df.dtypes

company                          object
location                         object
industry                         object
total_laid_off                  float64
percentage_laid_off             float64
date                     datetime64[ns]
stage                            object
country                          object
funds_raised_millions           float64
dtype: object

### Removing Duplicates

Next, we will remove the five duplicate rows identified during the data inspection process. Eliminating these duplicate records will ensure that each entry in the dataset is unique and prevent duplicate information from impacting our analysis.

In [41]:
# Remove duplicate rows
df = df.drop_duplicates()

# Verify duplicates were removed
duplicates = df.duplicated().sum()
print(f"Duplicate Rows Remaining: {duplicates}")

Duplicate Rows Remaining: 0

### Removing Leading/Trailing Spaces

Now, we will remove the leading and trailing spaces identified in the company column. Cleaning these formatting inconsistencies will help standardize company names and prevent issues when grouping, filtering, or analyzing the data.

In [42]:
# Remove leading and trailing spaces from the company column
df.loc[:, "company"] = df["company"].str.strip()

In [43]:
# Verify no leading/trailing spaces remain in the company column
spaces = (
    df["company"]
    .dropna()
    .astype(str)
    .str.startswith(" ")
    |
    df["company"]
    .dropna()
    .astype(str)
    .str.endswith(" ")
).sum()

print(f"Leading/Trailing Spaces Remaining: {spaces}")

Leading/Trailing Spaces Remaining: 0

Earlier, we identified three different naming conventions for the Crypto industry category and two different naming conventions for the United States country category.

To standardize these values, we will update any industry values that begin with "Crypto" to "Crypto" and any country values that begin with "United States" to "United States". This will consolidate duplicate categories and ensure consistency throughout the dataset.

In [44]:
# Standardize industry names to "Crypto"
df.loc[df["industry"].str.startswith("Crypto", na=False), "industry"] = "Crypto"

# Verify the update
print(sorted(df["industry"].dropna().unique()))

['Aerospace', 'Construction', 'Consumer', 'Crypto', 'Data', 'Education', 'Energy', 'Fin-Tech', 'Finance', 'Fitness', 'Food', 'HR', 'Hardware', 'Healthcare', 'Infrastructure', 'Legal', 'Logistics', 'Manufacturing', 'Marketing', 'Media', 'Other', 'Product', 'Real Estate', 'Recruiting', 'Retail', 'Sales', 'Security', 'Support', 'Transportation', 'Travel']

In [45]:
# Standardize country names to "United States"
df.loc[df["country"].str.startswith("United States", na=False), "country"] = "United States"

# Verify the update
print(sorted(df["country"].dropna().unique()))

['Argentina', 'Australia', 'Austria', 'Bahrain', 'Belgium', 'Brazil', 'Bulgaria', 'Canada', 'Chile', 'China', 'Colombia', 'Czech Republic', 'Denmark', 'Egypt', 'Estonia', 'Finland', 'France', 'Germany', 'Ghana', 'Greece', 'Hong Kong', 'Hungary', 'India', 'Indonesia', 'Ireland', 'Israel', 'Italy', 'Japan', 'Kenya', 'Lithuania', 'Luxembourg', 'Malaysia', 'Mexico', 'Myanmar', 'Netherlands', 'New Zealand', 'Nigeria', 'Norway', 'Pakistan', 'Peru', 'Poland', 'Portugal', 'Romania', 'Russia', 'Senegal', 'Seychelles', 'Singapore', 'South Africa', 'South Korea', 'Spain', 'Sweden', 'Switzerland', 'Thailand', 'Turkey', 'United Arab Emirates', 'United Kingdom', 'United States', 'Uruguay', 'Vietnam']

### Removing Null Values

Earlier we also found that our dataset had many null values in the **percentage_laid_off**, **total_laid_off**, and **total_funds_raised** columns. Since there are so many null values and there isn't an quick/easy way fill the data, we'll leave these as null for now.  


However, let's address the missing values in the **industry** column. As identified earlier, there are four rows where the industry value is null. We will examine these records to determine whether the same companies appear elsewhere in the dataset. If a company has multiple entries and one record contains an industry value while another is missing it, we can use the available information to update the null value and ensure consistency across the dataset.

In [46]:
# Get the companies with missing industry values
missing_companies = df.loc[df["industry"].isna(), "company"].unique()

# Display all records for each company
for company in missing_companies:
    print(f"Company: {company}")
    print(df[df["company"] == company])

Company: Airbnb
     company     location industry  total_laid_off  percentage_laid_off  \
8     Airbnb  SF Bay Area      NaN            30.0                  NaN
1936  Airbnb  SF Bay Area   Travel          1900.0                 0.25

           date           stage        country  funds_raised_millions
8    2023-03-03        Post-IPO  United States                 6400.0
1936 2020-05-05  Private Equity  United States                 5400.0
Company: Bally's Interactive
                 company    location industry  total_laid_off  \
330  Bally's Interactive  Providence      NaN             NaN

     percentage_laid_off       date     stage        country  \
330                 0.15 2023-01-18  Post-IPO  United States

     funds_raised_millions
330                  946.0
Company: Juul
     company     location  industry  total_laid_off  percentage_laid_off  \
736     Juul  SF Bay Area       NaN           400.0                  0.3
1937    Juul  SF Bay Area  Consumer           900.0                  0.3

           date    stage        country  funds_raised_millions
736  2022-11-10  Unknown  United States                 1500.0
1937 2020-05-05  Unknown  United States                 1500.0
Company: Carvana
      company location        industry  total_laid_off  percentage_laid_off  \
371   Carvana  Phoenix  Transportation             NaN                  NaN
659   Carvana  Phoenix  Transportation          1500.0                 0.08
1595  Carvana  Phoenix             NaN          2500.0                 0.12

           date     stage        country  funds_raised_millions
371  2023-01-13  Post-IPO  United States                 1600.0
659  2022-11-18  Post-IPO  United States                 1600.0
1595 2022-05-10  Post-IPO  United States                 1600.0

The companies missing an industry value are **Airbnb**, **Bally's Interactive**, **Juul**, and **Carvana**.

The good news is that Airbnb, Juul, and Carvana appear multiple times throughout the dataset, allowing us to use the industry values from their other records to fill in the missing entries and maintain consistency.

After researching Bally's Interactive, I determined that the company best fits within the Other industry category.

With this information, we can now update the dataset and fill in the missing values in the industry column.

In [47]:
# Update industry values for specific companies

df.loc[df["company"] == "Airbnb", "industry"] = "Travel"

df.loc[df["company"] == "Juul", "industry"] = "Consumer"

df.loc[df["company"] == "Carvana", "industry"] = "Transportation"

df.loc[df["company"] == "Bally's Interactive", "industry"] = "Other"

In [48]:
# Verify the updates
companies = ["Airbnb", "Juul", "Carvana", "Bally's Interactive"]

print(df[df["company"].isin(companies)].sort_values("company"))

                  company     location        industry  total_laid_off  \
8                  Airbnb  SF Bay Area          Travel            30.0
1936               Airbnb  SF Bay Area          Travel          1900.0
330   Bally's Interactive   Providence           Other             NaN
371               Carvana      Phoenix  Transportation             NaN
659               Carvana      Phoenix  Transportation          1500.0
1595              Carvana      Phoenix  Transportation          2500.0
736                  Juul  SF Bay Area        Consumer           400.0
1937                 Juul  SF Bay Area        Consumer           900.0

      percentage_laid_off       date           stage        country  \
8                     NaN 2023-03-03        Post-IPO  United States
1936                 0.25 2020-05-05  Private Equity  United States
330                  0.15 2023-01-18        Post-IPO  United States
371                   NaN 2023-01-13        Post-IPO  United States
659                  0.08 2022-11-18        Post-IPO  United States
1595                 0.12 2022-05-10        Post-IPO  United States
736                  0.30 2022-11-10         Unknown  United States
1937                 0.30 2020-05-05         Unknown  United States

      funds_raised_millions
8                    6400.0
1936                 5400.0
330                   946.0
371                  1600.0
659                  1600.0
1595                 1600.0
736                  1500.0
1937                 1500.0

Now, let's examine the stage column. There are six records with missing values in this field. Since there is not enough information available to accurately determine the company stage for these entries, the most appropriate solution is to assign these null values as **"Unknown"**.

In [49]:
# Change all columns that have stage value as null to unknown
df["stage"] = df["stage"].fillna("Unknown")

Finally, let's look at the **date** column. There was only one missing value in this field. Let's take a look at that record.

In [50]:
# Show row where the date is null
print(df[df["date"].isna()])

        company    location industry  total_laid_off  percentage_laid_off  \
2356  Blackbaud  Charleston    Other           500.0                 0.14

     date     stage        country  funds_raised_millions
2356  NaT  Post-IPO  United States                    NaN

After conducting additional research, I found that **Blackbaud** announced layoffs on **05/27/2020**. We can now update the missing date value to reflect this information and complete the dataset.

In [51]:
# Change null date value to 05/27/2020
df.loc[df["date"].isna(), "date"] = pd.Timestamp("2020-05-27")

# Verify there are no remaining null dates
print(df[df["date"].isna()])

Empty DataFrame
Columns: [company, location, industry, total_laid_off, percentage_laid_off, date, stage, country, funds_raised_millions]
Index: []